services:
  main:
    build:
      context: .
      dockerfile: dockerfile
    image: dedusproject
    command: npm run dev
    ports:
      - "8020:5173"
    volumes:
      - .:/app
      - /app/node_modules
